# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('branch', models.CharField(max_length=32)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='acc',
            name='status',
            field=models.CharField(default='user', max_length=8),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Task'),
        ),
    ]
