# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20170520_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Acc',
        ),
        migrations.RemoveField(
            model_name='task',
            name='branch',
        ),
        migrations.AddField(
            model_name='task',
            name='task_branch',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='testapp.Branch'),
        ),
    ]
